# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170118_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'matéria', 'verbose_name_plural': 'matérias'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'professor', 'verbose_name_plural': 'professores'},
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.IntegerField(verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.ManyToManyField(to='hello.Professor', verbose_name='professor(es)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sobrenome',
            field=models.CharField(max_length=100, verbose_name='sobrenome'),
        ),
    ]
