# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170118_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.CharField(max_length=4, verbose_name='sala')),
                ('departamento', models.CharField(max_length=50, verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Sala', verbose_name='sala'),
        ),
    ]
