# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20170123_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1, verbose_name='sexo'),
        ),
    ]
